discoveree/config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  get '/users/login', to: 'users#sign_in_page'
  post '/users/login', to: 'users#login'
  get '/users/signup', to: 'users#sign_up_page'
  post '/users', to: 'users#create', :as => 'sign_up'
  post '/categories/create' => 'categories#create'
  get '/users/logout', to: 'users#logout', :as => 'logout'

  resources :users do
    resources :categories, :except => ['create']
  end

  post '/categories/create' => 'categories#create'

  post '/categories/nodegraph' => 'categories#nodegraph'


  post "/categories/childnodes" => 'categories#childnodes'

  get '*missing' => redirect('/')

end

discoveree/app/models/user.rb
class User < ActiveRecord::Base
  has_many :categories, through: :contents
  has_many :contents
  has_secure_password

end

discoveree/app/controllers/users_controller.rb
class UsersController < ApplicationController

  include UserHelper

  def index
    redirect_to :root
  end

  def sign_in_page
  	render :sign_in, :layout => false
  end

  def sign_up_page
  	render :sign_up, :layout => false
  end

  def login
    @user = User.find_by(email: params[:user][:email])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user), flash: {notice: "Successful log in!"}
    else
      redirect_to users_path, flash: {notice: 'Invalid credentials!' }
    end
  end

  def create
    @user = User.new(user_params(params))
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user), flash: {notice: 'Successful log in!'}
    else
      redirect_to new_user_path, flash: {notice: 'Failed'}
    end
  end


  def show
    check_sign_in
    redirect_to user_categories_path(@current_user)
  end


  def logout
    session.clear
    redirect_to :root
  end

 private

  def user_params(params)
    params.require(:user).permit(:email, :password, :password_confirmation)
  end


end

discoveree/app/helpers/user_helper.rb
module UserHelper

  def is_signed_in?
    if !session[:user_id].nil?
      true
    else
      false
    end
  end

  def check_sign_in
    if is_signed_in?
      @current_user ||= User.find_by_id(session[:user_id])
    end 
  end 

  def validate_user_against params
    return true if @current_user.id == params
  end

  def sanity_check param
    p "*"*15
    p param
    p "*"*15
  end

end

discoveree/app/views/users/_index.html.erb
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
	</head>

<body>
<div id="fade">
</div>

	<header>
	<script src="http://threejs.org/build/three.min.js"></script>
	</header>


<div class="animation">
<script>nodes()</script>
</div>
<div id="welcome">

	<h3>expand your knowledge </h3>
	<h3>and visualize your interests</h3>
	<h3>with thoughtly</h3><br>
	<button id="get_started"><%= link_to "get started >>", users_login_path %></button><br><br>
</div>

</div>


	</body>
</html>

discoveree/app/views/users/index.html.erb
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
	</head>

<body>
<div id="fade">
</div>

	<header>
	<script src="http://threejs.org/build/three.min.js"></script>	
	</header>


<div class="animation">
<script>nodes()</script>
</div>
<div id="welcome">

	<h3>expand your knowledge </h3>
	<h3>and visualize your interests</h3>
	<h3>with thoughtly</h3><br>
	<button id="get_started"><%= link_to "get started >>", users_login_path %></button><br><br>
</div>

</div>


	</body>
</html>

discoveree/app/views/users/nodegraph.html.erb
<ul id="canvas_container">
	<% @list.each do |node| %>
	<li class="node"><%= node %></li>
	<% end %>
</ul>



<canvas id="viewport" height="800" width="800"></canvas>

discoveree/app/views/users/sign_in.html.erb
<!-- <div id="welcome"> -->
<%= form_for :user, :html=> { :id => "hello"}, url: {action: "login"} do |f| %>
	<h3>welcome, thinker</h3><br>
    <%= f.text_field :email, placeholder: "Email" %><br><br>
    <%= f.password_field :password, placeholder: "Password"  %><br><br>
      <button id="button"><%= f.submit "Sign Me In!"%></button><br><br>
    <%= link_to 'or create a new account', users_signup_path, :class => "event" %><br><br>  
<% end %>
<!-- </div> -->

discoveree/app/views/users/sign_up.html.erb
<!-- <div id="welcome"> -->
<%= flash[:notice] %>
    <%= form_for :user,  url: {action: "create"} do |f| %>

 <h3>welcome, thinker</h3><br/>
    <%= f.text_field :email, placeholder: "Email" %><br><br/>
    <%= f.password_field :password, placeholder: "Password" %><br><br>
    <%= f.password_field :password_confirmation, placeholder: "Confirm Password"  %><br><br>

    <button><%= f.submit "Sign Me Up!"%></button><br><br>
    <%= link_to "already signed up? sign in here", users_login_path, :class => "signin" %><br><br>
<% end %>

<!-- </div> -->